# optional
name: first

on: 
    pull_request:
        branches:
            - main
    workflow_dispatch:
    push:
        branches:
            - main

jobs:
    first-job:
        # OS, must specify tag
        runs-on: ubuntu-latest
        # functions you'd like to run
        steps:
            - name: print my name
              run: echo "ITI"